import pandas as pd
import numpy as np

def ROI(total_invested, final_portfolio_value):
    """
    Measures the overall return generated by the portfolio relative to the total amount invested.
    Higher values indicate better growth, while negative values indicate a loss.
    Args:
    - total_invested: float | The total amount of money invested.
    - final_portfolio_value: float | The final value of the portfolio.
    """
    score = ""

    if total_invested == 0:
        return 0, score
    roi = 100*(final_portfolio_value - total_invested)/total_invested

    if roi < 0 :
        score = "Bad"
    elif roi >= 0 and roi < 7 :
        score = "Insufficient"
    elif roi >= 7 and roi <= 12 :
        score = "Good"
    elif roi > 12 :
        score = "Excellent"

    return round(roi,2), score

def cumulative_return(nav_history):
    """
    Measures the total percentage gain or loss over the full period covered by the portfolio history.
    It is the simple change from the first value to the last value.
    Args:
    - nav_history : pd.Series
    """
    initial_nav = nav_history[0]
    final_nav = nav_history[-1]
    return ((final_nav - initial_nav) / initial_nav) * 100


def Max_Drawdown(worth_portfolio):
    """
    Measures the largest peak-to-trough decline experienced by the portfolio.
    A larger drawdown indicates deeper losses and higher risk of severe underperformance.
    Args:
    - worth_portfolio : pd.Series | Total worth of a portfolio for each date
    """
    score = ""
    
    running_max = worth_portfolio.cummax()
    drawdowns = (worth_portfolio - running_max) / running_max
    max_drawdown = 100*drawdowns.min()

    if max_drawdown < 0 and max_drawdown > -10 :
        score = "Excellent"
    elif max_drawdown <= -10 and max_drawdown > -25 :
        score = "Good"
    elif max_drawdown <= -25 and max_drawdown >= -40 :
        score = "High risk"
    elif max_drawdown < -40 :
        score = "Dangerous"

    return -max_drawdown, score


def daily_returns(series):
    """
    Computes the percentage change from one period to the next.
    These returns are used as the building blocks for risk-adjusted performance metrics.
    Args:
    - series (pd.Series): A series of numeric values.
    """
    if not isinstance(series, pd.Series):
        series = pd.Series(series)
    if len(series) < 2:
        return pd.Series(dtype=float)
    returns = series / series.shift(1) - 1
    return returns.dropna()


def alpha(benchmark_history, worth_portfolio, beta_portfolio):
    """
    Measures the excess return of the portfolio beyond what would be expected from its market exposure.
    A positive alpha suggests the strategy outperformed the benchmark after adjusting for risk.
    Args :
    - ROI_benchmark : float
    - ROI_portfolio : float
    - beta_portfolio : float
    """
    score = ""

    returns_benchmark = daily_returns(benchmark_history)
    returns_portfolio = daily_returns(worth_portfolio)
    Rf = 0.04
    Alpha = 100*(returns_portfolio.mean() - (Rf + beta_portfolio*(returns_benchmark.mean()-Rf)))

    if Alpha < 0 :
        score = "Bad"
    elif abs(Alpha) < 1e-6 :
        score = "Neutral"
    elif Alpha > 0 :
        score = "Good"
    
    return Alpha, score


def beta(benchmark_history, worth_portfolio):
    """
    Measures how sensitive the portfolio is to movements in the benchmark.
    A beta above 1 means the portfolio tends to move more than the benchmark, while a beta below 1 means it is less sensitive.
    Args :
    - benchmark_history : pd.Series
    - worth_portfolio : pd.Series
    """
    score = ""
    
    returns_benchmark = daily_returns(benchmark_history)
    returns_portfolio = daily_returns(worth_portfolio)

    covariance = returns_portfolio.cov(returns_benchmark)
    variance = returns_benchmark.var()
    Beta = covariance/variance

    if Beta < 0 :
        score = "Inverse"
    elif Beta > 0 and Beta < 0.8 :
        score = "Defensive"
    elif Beta > 0.8 and Beta < 1.2 :
        score = "Neutral"
    elif Beta > 1.2 :
        score = "Agressive"

    return Beta, score

def sharpe_ratio(worth_portfolio):
    """
    Measures the portfolio's excess return per unit of total volatility.
    Higher values indicate better risk-adjusted performance.
    Args:
    - worth_portfolio : pd.Series
    """
    score = ""
    
    returns = daily_returns(worth_portfolio)
    daily_risk_free = 0.04 / 252
    excess_return = returns.mean() - daily_risk_free
    SR = (excess_return / returns.std()) * np.sqrt(252)

    if SR < 1 :
        score = "Too much risk"
    elif SR > 1 and SR < 1.5 :
        score = "Acceptable"
    elif SR > 1.5 and SR < 2.0 :
        score = "Good"
    elif SR > 2.0 :
        score = "Excellent"

    return SR, score


def sortino_ratio(nav_history):
    """
    Measures a portfolio's excess return relative to downside risk only, ignoring upside volatility.
    It is often preferred over the Sharpe ratio when downside risk is the main concern.
    Args:
    - worth_portfolio : pd.Series
    """
    score = ""
    
    returns = daily_returns(nav_history)
    downside_returns = returns[returns < 0]
    if downside_returns.empty or downside_returns.std() == 0:
        return np.nan, score
    downside_volatility = downside_returns.std()
    daily_risk_free = 0.04 / 252
    excess_return = returns.mean() - daily_risk_free
    SR = (excess_return / downside_volatility) * np.sqrt(252)

    if SR < 1 :
        score = "Too much risk"
    elif SR > 1 and SR < 1.5 :
        score = "Acceptable"
    elif SR > 1.5 and SR < 2.0 :
        score = "Good"
    elif SR > 2.0 :
        score = "Excellent"
    
    return SR, score


def SMA(prices, window):
    """
    Simple Moving Average (SMA)
    Args:
    - prices: pd.Series | List of closing prices.
    - window: int | The number of periods to calculate the average over.
    Returns:
    - sma_values: pd.Series | List of SMA values
    """
    if window <= 0:
        raise ValueError("Window size must be a positive integer.")
    sma = prices.rolling(window=window).mean()
    return sma

def EMA(prices, window):
    """
    Exponential Moving Average (EMA)
    Args:
    - prices: pd.Series | List of closing prices.
    - window: int | The number of periods to calculate the average over.
    Returns:
    - ema: pd.Series | List of EMA values
    """
    if window <= 0:
        raise ValueError("Window size must be a positive integer.")
    ema = prices.ewm(span=window, adjust=False).mean()
    return ema

def MACD(prices, fast_period=12, slow_period=26, signal_period=9):
    """
    Moving Average Convergence Divergence (MACD)
    Args:
    - prices: pd.Series | List of closing prices.
    - fast_period: int | The number of periods for the fast EMA.
    - slow_period: int | The number of periods for the slow EMA.
    - signal_period: int | The number of periods for the signal line EMA.
    Returns:
    - macd_line: pd.Series | MACD line values
    - signal_line: pd.Series | Signal line values
    """
    if fast_period <= 0 or slow_period <= 0 or signal_period <= 0:
        raise ValueError("All periods must be positive integers.")
    
    ema_fast = EMA(prices, window=fast_period)
    ema_slow = EMA(prices, window=slow_period)
    macd_line = ema_fast - ema_slow
    signal_line = EMA(macd_line, window=signal_period)
    
    return macd_line, signal_line

def RSI(prices, window=14):
    """
    Relative Strength Index (RSI)
    Args:
    - prices: pd.Series | List of closing prices.
    - window: int | The number of periods to calculate the RSI over.
    Returns:
    - rsi: pd.Series | RSI values
    """
    if window <= 0:
        raise ValueError("Window size must be a positive integer.")
    
    delta = prices.diff()
    gain = delta.where(delta > 0, 0)
    loss = -delta.where(delta < 0, 0)

    avg_gain = EMA(gain, window=window)
    avg_loss = EMA(loss, window=window)

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    
    return rsi

def stochastic_oscillator(prices, k_window=14, d_window=3):
    """
    Stochastic Oscillator
    Args:
    - prices: pd.Series | List of closing prices.
    - k_window: int | The number of periods for %K calculation.
    - d_window: int | The number of periods for %D calculation (moving average of %K).
    Returns:
    - percent_k: pd.Series | %K values
    - percent_d: pd.Series | %D values
    """
    if k_window <= 0 or d_window <= 0:
        raise ValueError("Window sizes must be positive integers.")
    
    low_min = prices.rolling(window=k_window).min()
    high_max = prices.rolling(window=k_window).max()
    
    percent_k = 100 * ((prices - low_min) / (high_max - low_min))
    percent_d = percent_k.rolling(window=d_window).mean()
    
    return percent_k, percent_d

def std(prices, window):
    """
    Standard Deviation
    Args:
    - prices: pd.Series | List of closing prices.
    - window: int | The number of periods to calculate the standard deviation over.
    Returns:
    - std_dev: pd.Series | Standard deviation values
    """
    if window <= 0:
        raise ValueError("Window size must be a positive integer.")
    
    std_dev = prices.rolling(window=window).std()
    return std_dev

def ATR(prices_high, prices_low, prices_close, window=14):
    """
    Average True Range (ATR)
    Args:
    - prices_high: pd.Series | List of high prices.
    - prices_low: pd.Series | List of low prices.
    - prices_close: pd.Series | List of closing prices.
    - window: int | The number of periods to calculate the ATR over.
    Returns:
    - atr: pd.Series | ATR values
    """
    if window <= 0:
        raise ValueError("Window size must be a positive integer.")
    
    tr1 = prices_high - prices_low
    tr2 = (prices_high - prices_close.shift()).abs()
    tr3 = (prices_low - prices_close.shift()).abs()
    
    true_range = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    
    atr = true_range.rolling(window=window).mean()
    
    return atr

def VWAP(prices_high, prices_low, prices_close, volumes, window):
    """
    Volume Weighted Average Price (VWAP)
    Args:
    - prices_high: pd.Series | List of high prices.
    - prices_low: pd.Series | List of low prices.
    - prices_close: pd.Series | List of closing prices.
    - volumes: pd.Series | List of trading volumes.
    - window: int | The number of periods to calculate the VWAP over.
    Returns:
    - vwap: pd.Series | VWAP values
    """
    if window <= 0:
        raise ValueError("Window size must be a positive integer.")

    prices = (prices_high + prices_low + prices_close) / 3
    vwap = (prices * volumes).rolling(window=window).sum() / volumes.rolling(window=window).sum()
    
    return vwap